PROGRAM diagonalizaçao
IMPLICIT NONE
REAL(KIND=8):: A(3:3)
INTEGER::

A(1,1)=4.0d0
A(1,2)=2.0d0
A(1,3)=2.0d0
A(2,1)=2.0d0
A(2,2)=4.0d0
A(2,3)=2.0d0
A(3,1)=2.0d0
A(3,2)=2.0d0
A(3,3)=4.0d0

!PARA A PRIMEIRA CHAMADA 

ALLOCATE(WORK(1))
 CALL DSYEV( JOBZ "V", UPLO"U", 3, A, LDA"3", W, WORK, LWORK"-1", INFO )
DEALLOCATE(WORK)

!SEGUANDA CHAMADA 
ALLOCATE(LWORK)
 CALL DSYEV( v, U, 3, A, 3, W, WORK, LWORK, INFO )

!JOBZ- SERA 'N' AUTOVALORES E SERA 'V' SE FOR PRA CALCULAR OS AUTOVALORES E AUTOVETORES.
!UPLO- SERA 'U' O TRIANGULO SUPERIOR  É ARMAZENADO. E SERA 'V' SE O TRIANGULO INFERIOR DA MATRIZ A FOR ARMAZENADO.
!N- É A ORDEM DA MATRIZ A.
!A- É A MATRIZ A.
!LDA- A MAIOR DIMENÇÃO DA MATRIZ A.
!W- SE MANTEM CONSTANTE.
!WORK- SE MANTEM CONSTANTE.
!LWORK- O LWORK DA PRIMEIRA CHAMADA TERA O VALOR -1, JA O DA SEGUNDA SE MANTERÁ CONSTANTE.
!INFO- SE MANTERÁ CONSTANTE.



DO i=1, 3
write "autovalor",i, "=",w(i)
end do


DO i=1, 3
write "autovetor",i, "=", A(:,i)
end do 

